spring:
    # Spring Cloud Config Repo
    cloud:
        # Gateway routes settings
        gateway:
            routes:
                -   id: auth_routes
                    uri: ${AUTH_SERVICE_URL}
                    predicates:
                        - Path=/auth/**
                    filters:
                        - PrefixPath=/api/v1
                        - AddResponseHeader=X-Powered-By,APIGatewayService

                -   id: user_routes
                    uri: ${USER_SERVICE_URL}
                    predicates:
                        - Path=/user/**
                    filters:
                        - PrefixPath=/api/v1
                        - AddResponseHeader=X-Powered-By,APIGatewayService
                        -   name: JwtValidationFilter
        discovery:
            enabled: true

# JWT Configuration
jwt:
    validation:
        endpoint: /api/v1/auth/validate

# WebClient configuration
webclient:
    timeout: 5000

# Logging for gateway
logging:
    level:
        org.springframework.cloud.gateway: DEBUG