#JWT
auth:
    jwt:
        secret-key: ${AUTH_JWT_SECRET-KEY}

spring:
    # DataSource settings for postgresql
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    # Hibernate settings
    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}  # Fixed variable name
        properties:
            hibernate:
                dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}  # Fixed property structure
    
    # RabbitMQ settings
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        exchange:
            name: ${SPRING_RABBITMQ_EXCHANGE_NAME}
        routing:
            key: ${SPRING_RABBITMQ_ROUTING_KEY}
        queue:
            name: ${SPRING_RABBITMQ_QUEUE_NAME}

# Logging settings
logging:
    level:
        root: WARN
        com.example.authservice: TRACE
        org.springframework.security: ERROR

# Server settings
server:
    port: ${SERVER_PORT}

# Actuator settings
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"

# Eureka settings
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
