spring:
  #RabbitMQ settings
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  # SMTP config
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
# Server settings
server:
  port: ${SERVER_PORT}
# Resilience4j settings (retries)
resilience4j.retry:
  instances:
    emailService:
      maxAttempts: ${RESILIENCE4J_RETRY_INSTANCES_EMAILSERVICE_MAXATTEMPTS}
      waitDuration: ${RESILIENCE4J_RETRY_INSTANCES_EMAILSERVICE_WAITDURATION}
      retryExceptions:
        - org.springframework.mail.MailException
      exponentialBackoff:
        enabled: ${RESILIENCE4J_RETRY_INSTANCES_EMAILSERVICE_EXPONENTIALBACKOFF_ENABLED}
        multiplier: ${RESILIENCE4J_RETRY_INSTANCES_EMAILSERVICE_EXPONENTIALBACKOFF_MULTIPLIER}
#Logging settings
logging:
  level:
    org.springframework: ERROR
    com.example.mailingservice: TRACE
# Actuator settings
# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"