#JWT
auth:
    jwt:
        secret-key: ${AUTH_JWT_SECRET-KEY}

spring:
    # DataSource settings for postgresql
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    # Hibernate settings
    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DLL-AUTO}
        show-sql: true
        database-platform: ${SPRING_JPA_DATABASE-PLATFORM}

    # RabbitMQ settings
    rabbitmq:
        host: ${RABBITMQ_HOST}
        port: ${RABBITMQ_PORT}
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}

# Logging settings
logging:
    level:
        root: WARN
        com.example.authservice: TRACE
        org.springframework.security: ERROR

# Server settings
server:
    port: ${SERVER_PORT}

# Actuator settings
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"

# Eureka settings
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
