spring:
    cloud:
        gateway:
            routes:
                - id: eureka
                  uri: ${EUREKA_SERVER_URL} #IP:PORT
                  predicates:
                    - Path=/discovery/**
                  filters:
                    - AddResponseHeader=X-Powered-By,APIGatewayService
                    - AddRequestHeader=Authorization,${EUREKA_BASIC_AUTH}
                    - RewritePath=/discovery/(?<segment>.*),/eureka/${segment}
        discovery:
            enabled: true

# JWT Configuration
jwt:
    validation:
        endpoint: /api/v1/auth/validate

# WebClient configuration
webclient:
    timeout: 5000
    
# Eureka config
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true
        hostname: ${EUREKA_INSTANCE_HOSTNAME}
        ip-address: ${EUREKA_INSTANCE_IP_ADDRESS} # Your service's IP

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            show-details: always
        metrics:
            export:
                prometheus:
                    enabled: true

# Logging for gateway
logging:
    level:
        '[org.springframework.cloud.gateway]': INFO
        '[org.springframework.security]': INFO
    file:
        name: /var/log/api-gateway/application.log
        logback:
            rollingpolicy:
                max-file-size: 10MB
                max-history: 7
